[0m19:56:58.292551 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108d21af0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10963e810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10963e570>]}


============================== 19:56:58.294805 | aea8b194-ea78-4e96-911b-1da86f69ccb4 ==============================
[0m19:56:58.294805 [info ] [MainThread]: Running with dbt=1.9.0
[0m19:56:58.295054 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/umarbhaiyat/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt init', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:56:58.302558 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/Users/umarbhaiyat/.dbt')}
[0m19:56:58.302868 [info ] [MainThread]: Creating dbt configuration folder at 
[0m19:57:08.389179 [debug] [MainThread]: Starter project path: /opt/anaconda3/lib/python3.12/site-packages/dbt/include/starter_project
[0m19:57:08.396351 [info ] [MainThread]: 
Your new dbt project "data_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m19:57:08.396934 [info ] [MainThread]: Setting up your profile.
[0m19:58:30.960037 [info ] [MainThread]: Profile data_pipeline written to /Users/umarbhaiyat/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m19:58:30.968348 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 92.69571, "process_in_blocks": "0", "process_kernel_time": 1.199003, "process_mem_max_rss": "188743680", "process_out_blocks": "0", "process_user_time": 2.286695}
[0m19:58:30.969437 [debug] [MainThread]: Command `dbt init` succeeded at 19:58:30.969235 after 92.70 seconds
[0m19:58:30.970091 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1092a04a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b19ec00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11fe8d640>]}
[0m19:58:30.970844 [debug] [MainThread]: Flushing usage events
[0m19:58:31.820490 [debug] [MainThread]: An error was encountered while trying to flush usage events
